export const TYPE = {
    GET_ALL_BOOKS: "GET_ALL_BOOKS",
    GET_ALL_GENRE: "GET_ALL_GENRE",
    FILTER_BY_GENRE: "FILTER_BY_GENRE",
    FILTER_BY_PAGE: "FILTER_BY_PAGE",
    ADD_LIST_LECTURE: "ADD_LIST_LECTURE",
    REMOVE_BOOK: "REMOVE_BOOK",
    SET_LIST_LECTURE: "SET_LIST_LECTURE"
}


